name: Request indexing of a library
description: Request adding a new library or a new version of a library
title: "[Add a library]: "
labels: [ "index-request" ]
body:
  - type: markdown
    attributes:
      value: |
        ## Details
        
        Fill out the details of a library you want to be indexed by klibs.
        
        If you leave the version blank, all versions will be indexed.
  - type: input
    id: group_id
    attributes:
      label: Group ID
      placeholder: e.g., org.jetbrains.kotlinx
    validations:
      required: true
  - type: input
    id: artifact_id
    attributes:
      label: Artifact ID
      placeholder: e.g., kotlinx-coroutines-core
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., 1.10.2 (Leave blank if you want all versions)
    validations:
      required: false